import Head from "next/head";
import Wrapper from "@components/ui/wrapper";
import Section from "@components/ui/section";
import Button from "@components/ui/button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Minimal Landing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen flex items-center">
        <Section>
          <Wrapper>
            <h1 className="mb-8 max-w-4xl leading-snug">
              Crafting Unique Digital Experiences
            </h1>
            <p className="text-lg max-w-4xl leading-loose">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore
              aut alias velit quis deleniti sapiente itaque nobis dolorem
              voluptatum accusantium.
            </p>

            <div className="mt-8">
              <Button className="mr-4" accent href="/#work">
                See Work
              </Button>
              <Button href="/#contact">Contact</Button>
            </div>
          </Wrapper>
        </Section>
      </div>

      <div className="bg-gray-900">
        <Section></Section>
      </div>
    </>
  );
}
