import Head from "next/head";
import Link from "next/link";

import Wrapper from "@components/ui/wrapper";
import Section from "@components/ui/section";
import Button from "@components/ui/button";

import ReactIcon from "@components/icons/reactIcon";
import StylesIcon from "@components/icons/stylesIcon";
import GitIcon from "@components/icons/gitIcon";
import FigmaIcon from "@components/icons/figmaIcon";
import FramerIcon from "@components/icons/framerIcon";
import ArrowRightIcon from "@components/icons/arrowRightIcon";

const iconData = [
  {
    icon: <ReactIcon />,
    text: "Build using React and its frameworks such as Next, Redwood, Gatsby",
  },
  {
    icon: <StylesIcon />,
    text: "Style with modern CSS solutions like SCSS Modules, Tailwind, or PostCSS",
  },
  {
    icon: <GitIcon />,
    text: "Version control with Git and Github",
  },
  {
    icon: <FramerIcon />,
    text: "Animate with the Framer Motion library and CSS Keyframes",
  },
  {
    icon: <FigmaIcon />,
    text: "Wire frame and prototype with Figma",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Minimal Landing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen flex items-center">
        <Section>
          <Wrapper>
            <h1 className="mb-8 max-w-4xl leading-snug">
              Crafting Unique Digital Experiences
            </h1>
            <p className="text-xl max-w-4xl leading-loose">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore
              aut alias velit quis deleniti sapiente itaque nobis dolorem
              voluptatum accusantium.
            </p>

            <div className="mt-10">
              <Button className="mr-12" accent href="/#work">
                See Work
              </Button>
              <Link
                href="/#contact"
                className="inline-flex items-center text-white"
              >
                <span className="mr-4">Contact</span> <ArrowRightIcon />
              </Link>
            </div>
          </Wrapper>
        </Section>
      </div>

      <Section id="about" top={false}>
        <Wrapper>
          <div className="flex justify-between">
            <div className="flex-1 max-w-2xl">
              <h2 className="text-4xl font-normal leading-normal ">
                Building web apps to smb websites with smooth user experience
              </h2>
            </div>
            <div className="flex-1 max-w-2xl ml-16 mt-2">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Possimus quos ab repellat corrupti nemo sequi nobis vitae
                dolores quas!
              </p>
            </div>
            <div className="flex-1 max-w-2xl ml-10 mt-2">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Possimus quos ab repellat corrupti nemo sequi nobis vitae
                dolores quas!
              </p>
            </div>
          </div>

          <ul className="mt-32 flex gap-8">
            {iconData.map(({ icon, text }, i) => (
              <li key={i} className="flex-1 flex text-gray-200 flex-col">
                <span className="mr-4 mb-4 text-gray-600">{icon}</span>
                {text}
              </li>
            ))}
          </ul>
        </Wrapper>
      </Section>

      <Section id="work">
        <Wrapper>
          <h2 className="text-center mb-20">Recent Projects</h2>
          <div>
            <div>
              <p className="text-3xl">Name of Project</p>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum,
                natus hic facilis ea consequuntur quod odit mollitia officia
                explicabo aspernatur, accusamus odio quaerat aliquam voluptate,
                in unde tenetur voluptatibus illo reiciendis nisi.
              </p>
            </div>
          </div>
        </Wrapper>
      </Section>
    </>
  );
}
